lsi: false
safe: true
source:      .
includes:    ./_includes
baseurl: /-pooruss.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
collections:
  projects:
    output: true
